#!/usr/bin/env bash

#Compile bwtool from source.

git clone 'https://github.com/CRG-Barcelona/bwtool'
git clone 'https://github.com/CRG-Barcelona/libbeato'
git clone https://github.com/madler/zlib

cd libbeato/
git checkout 0c30432af9c7e1e09ba065ad3b2bc042baa54dc2
./configure
make

cd ../zlib
./configure
make

cd ../bwtool
./configure CFLAGS='-I../libbeato -I../zlib' LDFLAGS='-L../libbeato/jkweb -L../libbeato/beato -L../zlib'
make

if [[ -f "bwtool" ]]; then
	echo -e  "Removing intermediate files"
	rm -rf ../libbeato
	rm -rf ../zlib
	echo -e "-----------"
	echo -e "Done!\nPlease copy/move the bwtool binary (./bwtool/bwtool) to PATH or to a directory under PATH"
	echo -e "-----------"
else
	echo "Something went wrong!"
fi